title: Javascript
stripped: true
tabs: true

# icon: i-emojione:hatching-chick
# icon: i-game-icons:egg-eye
# icon: i-emojione:hatching-chick
# icon: i-openmoji:chicken
# icon: i-emojione:rooster
# icon: i-noto:owl
# icon: i-game-icons:rattlesnake
# icon: i-noto:phoenix
# icon: i-simple-icons:redragon
